### ISSUE TITLE
Constant freezes / crashes

### ISSUE THREAD

**Issue by RDIL** [HyperiumClient/Hyperium#526] opened 2018-10-31 01:40 UTC
**Describe the bug**  
Constant freezes / crashes.  This issue has been created on behalf of all the people who talk in #support.  If anybody has logs/screenshots, please attach them below!

**Comment by Sk1er** [comment] 2018-11-06 02:55
Made some big changes to how ticks are handled so I'll close this. If issues persist with the new framework, it can be reopened.

**Closed by Sk1er** 2018-11-06 02:55 UTC

**Comment by MGelgor** [comment] 2019-02-26 16:21
Crashes on mac during launch:

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
Caused by: java.lang.NoClassDefFoundError: adm
	at net.minecraft.client.main.Main.main(SourceFile:41)
	... 6 more
Caused by: java.lang.ClassNotFoundException: adm
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:267)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:165)
	... 9 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.hyperium.json:world.IMixinWorld] from phase [DEFAULT] in config [mixins.hyperium.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinApplyError(MixinTransformer.java:732)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:513)
	... 12 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ￄﾱsChunkLoaded(IIZ)Z in adm for mixins.hyperium.json:world.IMixinWorld->@Invoker[METHOD_PROXY]::callIsChunkLoaded(IIZ)Z
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:382)
	at org.spongepowered.asm.mixin.gen.InvokerInfo.findTargetMethod(InvokerInfo.java:62)
	at org.spongepowered.asm.mixin.gen.InvokerInfo.locate(InvokerInfo.java:58)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1214)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:918)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:308)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 12 more

**Comment by RDIL** [comment] 2019-02-26 16:23
Appears this was caused by a mixin not found:
```
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching ￄﾱsChunkLoaded(IIZ)Z in adm for mixins.hyperium.json:world.IMixinWorld->@invoker[METHOD_PROXY]::callIsChunkLoaded(IIZ)Z
```

**Comment by RDIL** [comment] 2019-02-26 16:24
@MGelgor please open a new issue for this.
