### ISSUE TITLE
Crashing when opening hyperium gui

### ISSUE THREAD

**Issue by aycy** [HyperiumClient/Hyperium#306] opened 2018-06-14 00:30 UTC
exception at cc.hyperium.gui.main.tabs.SettingsTab.<init>(SettingsTab.java:193)
`Hyperium.INSTANCE.getCosmetics()` is null

**Comment by datitisev** [comment] 2018-06-14 00:48
Duplicate of #305, which I opened just 20 minutes ago xD

**Comment by Sk1er** [comment] 2018-06-15 16:02
fixed for b14

**Closed by Sk1er** 2018-06-15 16:02 UTC
